[project]
channels = ["conda-forge"]
name = "oiio"
platforms = ["win-64"]

[tasks]



[feature.ocio.dependencies]
yaml-cpp="*"
zlib="*"

[feature.oiio.dependencies]
ffmpeg="*"
fmt="*"
freetype="*"
giflib="*"
libheif="*"
libjpeg-turbo="*"
libjxl="*"
libpng="*"
libraw="*"
libtiff="*"
libwebp="*"
openexr="*"
openjpeg="*"
tbb="*"
yaml-cpp="*"
zlib="*"

[environments]
ocio=["ocio"]
oiio=["oiio"]