name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-check:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      version: ${{steps.get-version.outputs.version}}
      need_build: ${{steps.check-new-version.outputs.need_build}}
    steps:
      - name: get-version
        id: get-version
        run: |
          $version=gh release view -R AcademySoftwareFoundation/OpenImageIO --json tagName -q .tagName
          Write-Output "openimageio: $version"
          echo "version=$version" >> "$env:GITHUB_OUTPUT"

      - name: check-new-version
        id: check-new-version
        run: |
          $current_versions=gh release view -R Glatzel/oiio --json tagName -q .tagName
          write-output $current_versions

          if("$current_versions".Contains("${{steps.get-version.outputs.version}}")){
            echo "need_build=false" >> "$env:GITHUB_OUTPUT"
            write-output "No new version found, skip build."
          }
          else{
            echo "need_build=true" >> "$env:GITHUB_OUTPUT"
            write-output "New version found, ${{steps.get-version.outputs.version}}"
          }

  release:
    # run this job when new version is found or push or pull_request
    # only create release on schedule or workflow_dispatch
    needs: version-check
    if: ${{needs.version-check.outputs.need_build =='true'|| github.event_name=='push'||github.event_name=='pull_request' }}
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: clone ocio and oiio
        run: ./scripts/clone-repo.ps1 "${{needs.version-check.outputs.version}}"

      - name: install vcpkg
        run: ./scripts/install-vcpkg-dep.ps1

      - name: build ocio
        run: ./scripts/build-ocio.ps1

      - name: build oiio
        run: ./scripts/build-oiio.ps1

      - name: copy item
        run: ./scripts/copy-item.ps1

      - name: pack
        run: Compress-Archive -Path ./openimageio -DestinationPath ./openimageio-windows-${{needs.version-check.outputs.version}}.zip -PassThru

      - name: Release
        if: ${{ github.event_name=='workflow_dispatch'||github.event_name=='schedule'  }}
        uses: softprops/action-gh-release@v2
        with:
          files: openimageio-windows-${{needs.version-check.outputs.version}}.zip
          tag_name: ${{needs.version-check.outputs.version}}
